// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:my_project/data/models/expense_category.dart';
import 'package:my_project/data/models/transaction.dart';
import 'package:my_project/data/models/transaction_type.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseCategoryAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseCategoryAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}
